import { randomBytes } from "node:crypto";
import { chmod, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const envPath = resolve(process.cwd(), ".env.local");

let existing = "";
try {
  existing = await readFile(envPath, "utf8");
} catch (error) {
  if (error?.code !== "ENOENT") throw error;
}

const presentKeys = new Set(
  existing
    .split(/\r?\n/)
    .map((line) => line.match(/^\s*([A-Z0-9_]+)\s*=/)?.[1])
    .filter(Boolean),
);

const defaults = [
  ["WORKLIFE_LOCAL_MODE", "true"],
  ["DATABASE_URL", "pglite:./data/morrow"],
  ["WORKLIFE_APP_URL", "http://localhost:3000"],
  ["WORKLIFE_SESSION_SECRET", randomBytes(32).toString("base64url")],
  ["CONNECTOR_ENCRYPTION_KEY", randomBytes(32).toString("base64")],
  ["CONNECTOR_ENCRYPTION_KEY_VERSION", "local-v1"],
  ["WORKLIFE_ENABLE_CONNECTOR_AUTHORIZATION", "true"],
  ["WORKLIFE_GMAIL_VERIFICATION_STATUS", "local_testing"],
  ["WORKLIFE_GOOGLE_CLIENT_ID", ""],
  ["WORKLIFE_GOOGLE_CLIENT_SECRET", ""],
  ["WORKLIFE_SLACK_CLIENT_ID", ""],
  ["WORKLIFE_SLACK_CLIENT_SECRET", ""],
  ["WORKLIFE_NOTION_CLIENT_ID", ""],
  ["WORKLIFE_NOTION_CLIENT_SECRET", ""],
  ["WORKLIFE_NOTION_VERSION", "2022-06-28"],
];

const missing = defaults.filter(([key]) => !presentKeys.has(key));
if (missing.length) {
  const prefix = existing.trim()
    ? `${existing.trimEnd()}\n\n`
    : "# Generated by npm run local:setup. Keep this file private.\n";
  const additions = missing
    .map(([key, value]) => `${key}=${value}`)
    .join("\n");
  await writeFile(envPath, `${prefix}${additions}\n`, {
    encoding: "utf8",
    mode: 0o600,
  });
  await chmod(envPath, 0o600);
}

console.log(
  missing.length
    ? `Configured ${missing.length} local setting${missing.length === 1 ? "" : "s"} in .env.local.`
    : ".env.local is already configured for local mode.",
);
console.log("");
console.log("Add provider credentials to .env.local, then restart npm run local:");
console.log("  Google: Gmail, Calendar, and Drive client ID + secret");
console.log("  Slack: client ID + secret");
console.log("  Notion: client ID + secret");
console.log("");
console.log("Register these exact callback URLs:");
for (const provider of ["gmail", "calendar", "drive", "slack", "notion"]) {
  console.log(
    `  http://localhost:3000/api/connectors/${provider}/callback`,
  );
}
