import type {
  ConnectorId,
  ContextSignal,
  ScheduleItem,
  WorkTask,
  WorkspaceSnapshot,
} from "@/lib/workspace/types";

function atOffset(
  now: Date,
  dayOffset: number,
  hour: number,
  minute = 0,
) {
  const result = new Date(now);
  result.setDate(result.getDate() + dayOffset);
  result.setHours(hour, minute, 0, 0);
  return result.toISOString();
}

function signal(
  id: string,
  connectorId: ConnectorId,
  label: string,
  detail: string,
  occurredAt: string,
): ContextSignal {
  return { id, connectorId, label, detail, occurredAt };
}

export function createDemoWorkspace(now = new Date()): WorkspaceSnapshot {
  const monthName = new Intl.DateTimeFormat("en-US", { month: "long" }).format(
    now,
  );
  const tasks: WorkTask[] = [
    {
      id: "task-atlas-launch",
      title: "Prepare the Atlas launch decision",
      project: "Atlas launch",
      area: "Work",
      importance: "major",
      status: "open",
      dueAt: atOffset(now, 0, 16, 30),
      estimateMinutes: 90,
      sourceIds: ["slack", "granola", "calendar"],
      signals: [
        signal(
          "signal-atlas-slack",
          "slack",
          "#atlas-launch",
          "Four sample replies surfaced a scope decision.",
          atOffset(now, 0, 8, 42),
        ),
        signal(
          "signal-atlas-granola",
          "granola",
          "Launch readiness review",
          "Sample note: decide whether analytics ships in v1.",
          atOffset(now, -1, 15, 30),
        ),
        signal(
          "signal-atlas-calendar",
          "calendar",
          "Decision review",
          "A sample 30-minute review is on today’s calendar.",
          atOffset(now, 0, 15, 30),
        ),
      ],
      rationale:
        "High-impact decision with three recent context signals and a same-day review.",
      createdAt: atOffset(now, -3, 10),
      isSample: true,
    },
    {
      id: "task-renewal-proposal",
      title: "Review the Northstar renewal proposal",
      project: "Customer growth",
      area: "Work",
      importance: "major",
      status: "open",
      dueAt: atOffset(now, 0, 18),
      estimateMinutes: 45,
      sourceIds: ["gmail", "calendar"],
      signals: [
        signal(
          "signal-renewal-email",
          "gmail",
          "Sample email thread",
          "The pricing attachment is waiting for your review.",
          atOffset(now, 0, 7, 55),
        ),
        signal(
          "signal-renewal-calendar",
          "calendar",
          "Renewal follow-up",
          "A sample follow-up is scheduled tomorrow morning.",
          atOffset(now, -1, 12),
        ),
      ],
      rationale:
        "Revenue-sensitive work that is due today and blocks tomorrow’s conversation.",
      createdAt: atOffset(now, -2, 14),
      isSample: true,
    },
    {
      id: "task-candidate-feedback",
      title: "Send candidate feedback",
      project: "Team",
      area: "Work",
      importance: "minor",
      status: "open",
      dueAt: atOffset(now, 0, 13),
      estimateMinutes: 20,
      sourceIds: ["gmail", "granola"],
      signals: [
        signal(
          "signal-candidate-granola",
          "granola",
          "Interview debrief",
          "A sample note has the key strengths and open concern.",
          atOffset(now, -1, 16),
        ),
      ],
      rationale: "A quick commitment that is now overdue.",
      createdAt: atOffset(now, -1, 16),
      isSample: true,
    },
    {
      id: "task-eye-exam",
      title: "Book the annual eye exam",
      project: "Life admin",
      area: "Wellbeing",
      importance: "minor",
      status: "open",
      dueAt: atOffset(now, 0, 19),
      estimateMinutes: 10,
      sourceIds: ["manual"],
      signals: [],
      rationale: "A ten-minute personal task due today.",
      createdAt: atOffset(now, -4, 9),
      isSample: true,
    },
    {
      id: "task-hiring-plan",
      title: "Shape the Q4 hiring plan",
      project: "Team",
      area: "Work",
      importance: "major",
      status: "open",
      dueAt: atOffset(now, 2, 15),
      estimateMinutes: 120,
      sourceIds: ["slack", "granola"],
      signals: [
        signal(
          "signal-hiring-slack",
          "slack",
          "Sample leadership thread",
          "Headcount trade-offs need an owner before Monday.",
          atOffset(now, 0, 9, 5),
        ),
        signal(
          "signal-hiring-granola",
          "granola",
          "Planning review",
          "Sample notes captured three open role decisions.",
          atOffset(now, -2, 11),
        ),
      ],
      rationale: "Strategic work with active leadership discussion.",
      createdAt: atOffset(now, -5, 11),
      isSample: true,
    },
    {
      id: "task-customer-themes",
      title: "Consolidate customer interview themes",
      project: "Research",
      area: "Work",
      importance: "minor",
      status: "open",
      dueAt: atOffset(now, 3, 17),
      estimateMinutes: 40,
      sourceIds: ["granola", "manual"],
      signals: [
        signal(
          "signal-research-granola",
          "granola",
          "Three sample customer calls",
          "Notes are ready to organize once an export is supplied.",
          atOffset(now, -1, 14),
        ),
      ],
      rationale: "Recent customer context is ready to synthesize.",
      createdAt: atOffset(now, -3, 14),
      isSample: true,
    },
    {
      id: "task-monthly-finances",
      title: `Close ${monthName} finances`,
      project: "Operations",
      area: "Work",
      importance: "major",
      status: "open",
      dueAt: atOffset(now, 5, 16),
      estimateMinutes: 75,
      sourceIds: ["gmail", "manual"],
      signals: [
        signal(
          "signal-finance-email",
          "gmail",
          "Sample receipt digest",
          "Two items are marked as needing a category.",
          atOffset(now, -1, 8),
        ),
      ],
      rationale: "A month-end obligation with a fixed deadline.",
      createdAt: atOffset(now, -7, 9),
      isSample: true,
    },
    {
      id: "task-training-plan",
      title: "Plan October training rhythm",
      project: "Personal growth",
      area: "Wellbeing",
      importance: "minor",
      status: "open",
      dueAt: atOffset(now, 6, 18),
      estimateMinutes: 25,
      sourceIds: ["calendar", "manual"],
      signals: [],
      rationale: "Keeps personal commitments visible beside work.",
      createdAt: atOffset(now, -2, 18),
      isSample: true,
    },
    {
      id: "task-completed-agenda",
      title: "Share the launch review agenda",
      project: "Atlas launch",
      area: "Work",
      importance: "minor",
      status: "completed",
      dueAt: atOffset(now, 0, 9),
      estimateMinutes: 10,
      sourceIds: ["slack"],
      signals: [],
      rationale: "Completed sample task.",
      createdAt: atOffset(now, -1, 17),
      isSample: true,
    },
  ];

  const schedule: ScheduleItem[] = [
    {
      id: "schedule-standup",
      title: "Product stand-up",
      startAt: atOffset(now, 0, 9, 30),
      endAt: atOffset(now, 0, 9, 55),
      kind: "meeting",
      sourceId: "calendar",
      attendees: 7,
      isSample: true,
    },
    {
      id: "schedule-focus",
      title: "Atlas decision · focus block",
      startAt: atOffset(now, 0, 10, 30),
      endAt: atOffset(now, 0, 12),
      kind: "focus",
      sourceId: "calendar",
      isSample: true,
    },
    {
      id: "schedule-lunch",
      title: "Lunch away from desk",
      startAt: atOffset(now, 0, 12, 30),
      endAt: atOffset(now, 0, 13, 15),
      kind: "personal",
      sourceId: "manual",
      isSample: true,
    },
    {
      id: "schedule-review",
      title: "Launch decision review",
      startAt: atOffset(now, 0, 15, 30),
      endAt: atOffset(now, 0, 16),
      kind: "meeting",
      sourceId: "calendar",
      attendees: 4,
      isSample: true,
    },
    {
      id: "schedule-walk",
      title: "Reset walk",
      startAt: atOffset(now, 0, 17, 30),
      endAt: atOffset(now, 0, 18),
      kind: "personal",
      sourceId: "manual",
      isSample: true,
    },
    {
      id: "schedule-renewal",
      title: "Northstar renewal follow-up",
      startAt: atOffset(now, 1, 10),
      endAt: atOffset(now, 1, 10, 30),
      kind: "meeting",
      sourceId: "calendar",
      attendees: 3,
      isSample: true,
    },
    {
      id: "schedule-planning",
      title: "Weekly planning",
      startAt: atOffset(now, 3, 16),
      endAt: atOffset(now, 3, 16, 45),
      kind: "focus",
      sourceId: "manual",
      isSample: true,
    },
    {
      id: "schedule-finance",
      title: "Month-end close block",
      startAt: atOffset(now, 5, 14),
      endAt: atOffset(now, 5, 15, 30),
      kind: "focus",
      sourceId: "manual",
      isSample: true,
    },
  ];

  return {
    tasks,
    schedule,
    generatedAt: now.toISOString(),
    isSample: true,
  };
}
